export const printersApi = {
  listByHospital: (hospitalId: string) => `/printers/hospitals/${hospitalId}`,
  list: `/printers`,
  sync: `/printers/sync`,
  refresh: `/printers/sync/request`,
  refreshStatus: (operationId: string) => `/agent/printers/refresh/${operationId}`,
  detail: (id: string) => `/printers/${id}`,
  createPrintJob: (printerId: string) => `/printers/${printerId}/jobs`,
  create: "/printers",
  update: (id: string) => `/printers/${id}`,
  delete: (id: string) => `/printers/${id}`,
  updateDisplayName: (id: string) => `/printers/${id}/display-name`,
  test: (id: string) => `/printers/${id}/test`,
  settings: "/printers/settings",
  settingsDefaults: "/printers/settings/defaults",
  settingsOverrides: "/printers/settings/overrides",
  settingsOverride: (overrideId: string) => `/printers/settings/overrides/${overrideId}`,
  print: "/printers",
};
